obj-$(CONFIG_CRYPTO_DEV_EIP93) += crypto-hw-eip93.o

crypto-hw-eip93-y += eip93-main.o eip93-common.o

crypto-hw-eip93-$(CONFIG_CRYPTO_DEV_EIP93_SKCIPHER) += eip93-cipher.o
#crypto-hw-eip93-$(CONFIG_CRYPTO_DEV_EIP93_AES) += eip93-aes.o
#crypto-hw-eip93-$(CONFIG_CRYPTO_DEV_EIP93_DES) += eip93-des.o
crypto-hw-eip93-$(CONFIG_CRYPTO_DEV_EIP93_AEAD) += eip93-aead.o

